# Generated by Django 3.1.4 on 2021-03-16 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_basket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicBasketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Dynamic product',
                'verbose_name_plural': 'Dynamic products',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='basebasket',
            name='basket_items',
            field=models.ManyToManyField(blank=True, related_name='basket', to='django_basket.DynamicBasketItem', verbose_name='Basket item'),
        ),
    ]
